### ISSUE TITLE
Docker container startup time

### ISSUE THREAD

**Issue by dimaqq** [scylladb/scylla#10007]
I'm trying to use Scylla, again, and I've observed that the db startup time in the container is quite long.

My config:
```yaml
version: "3.9"
services:
  scylladb:
    image: scylladb/scylla
    volumes:
      - type: bind
        source: .data-scylladb
        target: /var/lib/scylla
        consistency: delegated
    ports:
      - "9042:9042"  # native CQL
      - "9142:9142"  # over SSL
      - "10000:10000"  # REST API
      - "9100:9100"  # node explorer
      - "9160:9160"  # thrift
      - "19042:19042"  # shard-aware native CQL
      - "19142:19142"  # shard-aware native CQL
    command: --smp=1
```

There's no logical data in the volume, I haven't even created a key space yet; after starting the docker compose environment a few times, there's a bunch of files in the volume:

```command
> du -hs .data-scylladb/
66M	.data-scylladb/
```

It takes ~17s from `docker-compose up --build` until I can connect with `cqlsh` from the host.
It takes ~3.5s to shut down the compose environment.

If I remove all the data from the volume, it takes Scylla 24s to start (until `cqlsh` can connect).

I was hoping to use Scylla as a database for functional tests for my Python code, but 17 or 24 seconds startup time is a rather bitter pill to swallow.

Looking through host `vmstat 1`, the "user" share of CPU usage spikes to 11% for maybe 1.5s only, the rest of the time the system is idle. Same for block IO, one spike <2s and one spike <1s; idle rest of the time. What is Scylla waiting for?

Is there perhaps some shortcut to bring a test Scylla container up quicker?
