### ISSUE TITLE
Bootstrap performance issue

### ISSUE THREAD

**Issue by AdamNuclear** [scylladb/scylla#1731]
_Installation details_
Scylla version (or git commit hash): 1.3.1-20160923.ff67439
Cluster size: 10->14
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04 LTS

_Hardware details (for performance issues)_: Xeon E5-1650 v3, 256GB RAM, 2x480GB ssd md raid 0
Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets=1 cores=6 hyperthreading=12 memory=256GB
Disks: (SSD/HDD, count) 2xSAMSUNG MZ7WD480 raid 0 

I found some problem during bootstraping new nodes.
We have actually 10 nodes in 2DC's.

That DC's are actually buildings in same location connected over good network so all servers are able to communicate over 1Gbit network so I decided to use scylla as 1DC but different racks with GossipingPropertyFileSnitch.

```
UN  <ip>   ?          256     ?       e54bd15e-ca1b-47dd-b32b-fef60db019a4  RAC2
UN  <ip>   ?          256     ?       618bf929-4a48-4208-93ea-94bded2ac20d  RAC1
UJ  <ip>   0 bytes    256     ?       b2a21f57-7900-4cc4-ad28-fe2455fa4103  RAC1
UN  <ip>  ?          256     ?       5135b659-c105-45af-8071-716fe56c95f3  RAC1
UN  <ip>   ?          256     ?       f0e9e917-1d95-44bd-9a8c-f5fba3d576cb  RAC1
UN  <ip>    ?          256     ?       5b806f40-05e9-4673-a351-3464287fd8d8  RAC2
UN  <ip>  ?          256     ?       9f10f5f5-d224-4fa6-93d4-1e32fd9258be  RAC2
UN  <ip>   ?          256     ?       b72473c2-0471-405d-95ab-355fb1458c63  RAC1
UN  <ip>    ?          256     ?       8fb35e0e-3f67-416a-ac91-069aee6d4591  RAC1
UN  <ip>   ?          256     ?       ec2834ec-2817-448c-90db-430f1a9cc1d7  RAC2
UN  <ip>   ?          256     ?       5761c9fe-b2d0-47c3-be88-cd39874e0fc6  RAC2
```

3 servers in each "rack" are assign as seed provider so I have 6 seeds servers.

All servers have load ~200GB and when I am trying to join another node the network is going around from beginning 900-980Mbit/s and than after few minutes it drop to 150-200Mbit which is normal traffic between nodes during standard usage but node is still joining more than 6h and its still joining. I want to extend cluster with new 4 nodes but it's slow as hell. Is there any way how to speedup cluster bootstraping ? 

scylla.yaml:

```
cluster_name: 'my_cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "<ip1>,<ip2>,<ip3>,<ip4>,<ip5>,<ip6>"
listen_address: <ip>
native_transport_port: 9042
stream_throughput_outbound_megabits_per_sec: 500
read_request_timeout_in_ms: 10000
write_request_timeout_in_ms: 5000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: <ip>
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/
```

cassandra-rackdc.properties:

```
dc=DC1
rack=RAC1
```
