### ISSUE TITLE
docs: Issue on page Certificate-based Authentication

### ISSUE THREAD

**Issue by tluck** [scylladb/scylla#24636]
I would like to report an issue on page https://docs.scylladb.com/manual/master/operating-scylla/security/certificate-authentication

### Problem

Add and example for ALTNAME in the example as SUBJECT in certs is soon to be fully deprecated.

###  Suggest a fix
add this to the example for role mapping in section 3.

```
    auth_certificate_role_queries:
      - source: ALTNAME
        query: DNS=([^,\s]+)
      - source: SUBJECT
        query: CN\s*=\s*([^,\s]+)

```
