### ISSUE TITLE
[Bug]: .cassandra permission denied

### ISSUE THREAD

**Issue by Jimflip** [scylladb/scylla#24753]
### Code of Conduct

- [x] I have read the disclaimer above and am reporting a suspected malfunction in Scylla.

### product version

latest docker image

### Cluster Size

1

### OS

Ubuntu

### Additional Environmental Data

running docker compose

### Reproduction Steps

The steps to reproduce the problem are: start up docker image

### What is the problem?

The problem is that, failing to start when running docker image

### Expected behavior?

I expected that not that.

### Relevant log output

```shell
File "/scyllasetup.py", line 79, in cqlshrc
out:-scylla       |     self._run(["mkdir", "-p",  "%s/.cassandra" % home])
out:-scylla       |     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
out:-scylla       |   File "/scyllasetup.py", line 39, in _run
out:-scylla       |     subprocess.check_call(*args, **kwargs)
out:-scylla       |     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
out:-scylla       |   File "/opt/scylladb/python3/lib64/python3.13/subprocess.py", line 421, in check_call
out:-scylla       |     raise CalledProcessError(retcode, cmd)
out:-scylla       | subprocess.CalledProcessError: Command '['mkdir', '-p', '/var/lib/scylla/.cassandra']' returned non-zero exit status 1.
out:-scylla       | running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
out:-scylla       | running: (['/opt/scylladb/scripts/scylla_io_setup'],)
out:-scylla       | running: (['mkdir', '-p', '/var/lib/scylla/.cassandra'],)
out:-scylla       | mkdir: cannot create directory ‘/var/lib/scylla/.cassandra’: Permission denied
out:-scylla       | failed!
out:-scylla       | Traceback (most recent call last):
out:-scylla       |   File "/docker-entrypoint.py", line 28, in <module>
out:-scylla       |     setup.cqlshrc()
out:-scylla       |     ~~~~~~~~~~~~~^^
out:-scylla       |   File "/scyllasetup.py", line 79, in cqlshrc
out:-scylla       |     self._run(["mkdir", "-p",  "%s/.cassandra" % home])
out:-scylla       |     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
out:-scylla       |   File "/scyllasetup.py", line 39, in _run
out:-scylla       |     subprocess.check_call(*args, **kwargs)
out:-scylla       |     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
out:-scylla       |   File "/opt/scylladb/python3/lib64/python3.13/subprocess.py", line 421, in check_call
out:-scylla       |     raise CalledProcessError(retcode, cmd)
out:-scylla       | subprocess.CalledProcessError: Command '['mkdir', '-p', '/var/lib/scylla/.cassandra']' returned non-zero exit status 1.
```

**Comment by mykaul** [comment]
@Jimflip - thanks for filing the issue, but please provide more information. What docker compose did you use, which Scylla version did you use, how did you run docker compose, etc. Please rephrase the title as well.

**Comment by michaelmalonenz** [comment]
I have also experienced this issue.  I got it when starting a new instance of scylladb in order to use as a local DynamoDB with better perf than SQLite.  I've previously had this configuration working just fine for over a year, but starting from fresh gives me the aforementioned error.

Docker-Compose version: `Docker Compose version v2.38.2-desktop.1`
Docker-Desktop version: `4.43.2` (most recent at the time of writing)

Running `scylladb/scylla:latest` image details:
<img width="1142" height="1161" alt="Image" src="https://github.com/user-attachments/assets/c022e51b-56cc-4f1f-903b-c911572f18a5" />

relevant portion of the docker compose file I'm using:
```yaml
  # a drop-in replacement for DynamoDB-local, but with much better performance
  # see https://opensource.docs.scylladb.com/stable/alternator/alternator.html for details
  scylladb-local:
    image: scylladb/scylla
    restart: always
    container_name: scylladb-local
    command: --alternator-port=8005 --alternator-write-isolation=only_rmw_uses_lwt --memory=4G
    ports:
      - 8005:8005 # port 8000 is occupied by uniFlow already
    volumes:
      - "scylla-data:/var/lib/scylla"
    networks:
      - screening-net

volumes:
  opensearch-data1:
  opensearch-data2:
  scylla-data:
networks:
  screening-net:
    name: screening-net
```

Host system is Windows 11 Pro 24H2
