### ISSUE TITLE
Could not initialize seastar: std::out_of_range (_Map_base::at)

### ISSUE THREAD

**Issue by MasterGroosha** [scylladb/scylla#3779]
- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3.0-0.20180917.178f870a0
Cluster size: 1 host (standalone mode)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.1

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): Physical
Disks: (SSD/HDD, count) 5 disks as RAID-0 (xfs) + 1 disk as ext4 for commit log

Fresh installation of ScyllaDB doesn't start with exception in title. Performed scylla_setup and scylla_io_setup.

`io.conf` file:
`SEASTAR_IO="--num-io-queues=1 --io-properties-file=/etc/scylla.d/io_properties.yaml"`

`io_properties.yaml` file:
```
disks:
  - mountpoint: /media/scylla/data # This directory exists and has 777 rights (for testing)
    read_iops: 826
    read_bandwidth: 519884480
    write_iops: 1058
    write_bandwidth: 618628672
```

part of `scylla.yaml` config file:
```
data_file_directories:
    - /media/scylla/data

commitlog_directory: /media/scylla-logs/commitlog # this dir also exists with the same rights
```

However when I run `systemctl start scylla-server`, I see the following error in journalctl:
```
Sep 25 08:07:56 server scylla[8235]: Could not initialize seastar: std::out_of_range (_Map_base::at)\
Sep 25 08:07:56 server systemd[1]: scylla-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 25 08:07:56 server systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Sep 25 08:07:56 server systemd[1]: Failed to start Scylla Server.
```

Unfortunately I don't see any other errors anywhere, there's no `scylla` directory in `/var/log`. `kern.log` and `syslog` show me no new information about scylla. Could you please assist me in troubleshooting this problem and finding a cause of it? 
Upd: looks like sometimes Scylla produces backtrace as shown in #3636, how can I see it in my case?
