### ISSUE TITLE
Currently no support for docker swarm

### ISSUE THREAD

**Issue by vlizanae** [scylladb/scylla#4232]
I have been trying to deploy scylla on docker swarm but seems rather impossible for a couple of reasons:
- As you can see in this [issue](https://github.com/moby/moby/issues/24170), docker services cannot be assigned static IPs, and there are some points at scylla configuration that still do not support DNS.
- The examples I have stumbled upon of compose files for swarm use deprecated features, for instance you can no longer use bridge networks for swarm services.
- Even the environment variables for the services seem to be broken, I had set `SEEDS="10.0.23.1,10.0.23.1"` only to find when accessing the container that the `/etc/scylla/scylla.yaml` still had localhost in its seeds parameter. I tried mounting a `scylla.yaml` as volume but even then the nodes keep starting as seeds when they are not.

**Comment by tzach** [comment]
Thanks @vlizanae 

What Scylla version are you using?

> * As you can see in this [issue](https://github.com/moby/moby/issues/24170), docker services cannot be assigned static IPs, and there are some points at scylla configuration that still do not support DNS.

Scylla support URL as Seed since 2.0 release #2357
If it does not works for you, please attach the docker logs


> * The examples I have stumbled upon of compose files for swarm use deprecated features, for instance you can no longer use bridge networks for swarm services.

Very good point and we should fix that.
Can you please point us to these examples?

> * Even the environment variables for the services seem to be broken, I had set `SEEDS="10.0.23.1,10.0.23.1"` only to find when accessing the container that the `/etc/scylla/scylla.yaml` still had localhost in its seeds parameter. I tried mounting a `scylla.yaml` as volume but even then the nodes keep starting as seeds when they are not.


Overriding scylla.yaml should work
See here https://docs.scylladb.com/operating-scylla/procedures/tips/best_practices_scylla_on_docker/#overriding-scylla-yaml-with-a-master-file
Here as well, logs will help

**Comment by vlizanae** [comment]
Thanks for the quick reply, `scylla --version` is `3.0.3-0.20190211.c36c58c64`. My first configuration with urls was the following:

---
docker-compose.yml:
```yml
version: '3.3'

services:

  scylla1:
    image: scylladb/scylla
    entrypoint: /docker-entrypoint.py --memory=32G
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip13]
    networks:
      - nets_backend
    volumes:
      - /data/local/scylla/config/scylla.yaml:/etc/scylla/scylla.yaml
      - /data/local/scylla/data:/var/lib/scylla/data
      - /data/local/scylla/commitlog:/var/lib/scylla/commitlog

  scylla2:
    image: scylladb/scylla
    entrypoint: /docker-entrypoint.py --memory=32G
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip17]
    networks:
      - nets_backend
    volumes:
      - /data/local/scylla/config/scylla.yaml:/etc/scylla/scylla.yaml
      - /data/local/scylla/data:/var/lib/scylla/data
      - /data/local/scylla/commitlog:/var/lib/scylla/commitlog

  scylla3:
    image: scylladb/scylla
    entrypoint: /docker-entrypoint.py --memory=32G
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip18]
    networks:
      - nets_backend
    volumes:
      - /data/local/scylla/config/scylla.yaml:/etc/scylla/scylla.yaml
      - /data/local/scylla/data:/var/lib/scylla/data
      - /data/local/scylla/commitlog:/var/lib/scylla/commitlog

networks:
  nets_backend:
    external: true
# nets_backend defined in nets compose file as follows:
# networks:
#   backend:
#     driver: overlay
#     attachable: true
```
---
/data/local/scylla/config/scylla.yaml (all hosts):
```
...
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "scylla1,scylla2"

# Commented for scylla to get an address as I can't assign a static ip to a service
#listen_address: localhost
...
```
---

The thing is that from my understanding, when scylla gets the address it should get the container's one, and not the service's.

nodetool status example:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.0.23.29  3.35 MB    256          ?       1b8afb57-13e0-4013-8733-dfc579246e6b  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

logs:
[scylla1.log](https://github.com/scylladb/scylla/files/2873050/scylla1.log)
[scylla2.log](https://github.com/scylladb/scylla/files/2873051/scylla2.log)
[scylla3.log](https://github.com/scylladb/scylla/files/2873052/scylla3.log)

The examples I found were on `scylla-code-samples` repo, mainly [mms](https://github.com/scylladb/scylla-code-samples/blob/master/mms/docker-compose.yml) and [elasticsearch-scylla](https://github.com/scylladb/scylla-code-samples/blob/master/elasticsearch-scylla/docker-compose.yml)

hope it helps.
