### ISSUE TITLE
Scylla does not start when trying to load mc sstables.

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla#4318]
## When trying to load C* sstables to a scylla node, scylla does not start.

*Installation details*
Scylla version (or git commit hash): 3.0.3-0.20190211.c36c58c64 
Cluster size: 1 node (i3.16xl)
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.6.1810 / AMI: ami-05f62259c7715e1a6 (Ireland)

### Trying to process mc sstables fails

scylla.yaml
```
cluster_name: migration
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    # Addresses of hosts that are deemed contact points. 
    # Scylla nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds: "172.31.20.104"
listen_address: 172.31.20.104
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: 172.31.20.104
 
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/
auto_bootstrap: true
enable_sstables_mc_format: true
```

Error: 
```
Mar 10 15:47:55 ip-172-31-20-104.eu-west-1.compute.internal scylla[45349]: scylla: sstables/leveled_manifest.hh:395: static std::vector<seastar::lw_shared_ptr<sstables::sstable> > leveled_manifest::overlapping(const schema&, dht::token, dht::token, const T&) [with T = std::vector<seastar::lw_shared_ptr<sstables::sstable> >]: Assertion `start <= end' failed.
```
[Backtrace #0]
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-3.0.3/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-3.0.3/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-3.0.3/seastar/core/reactor.cc:431
seastar::print_with_backtrace(char const*) at /usr/src/debug/scylla-3.0.3/seastar/core/reactor.cc:438
sigabrt_action at /usr/src/debug/scylla-3.0.3/seastar/core/reactor.cc:4024
 (inlined by) operator() at /usr/src/debug/scylla-3.0.3/seastar/core/reactor.cc:4006
 (inlined by) _FUN at /usr/src/debug/scylla-3.0.3/seastar/core/reactor.cc:4002
system at ??:?
__bsd_signal at :?
__GI_abort at :?
__assert_fail_base at :?
__assert_fail_base at :?
std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > leveled_manifest::overlapping<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > >(schema const&, dht::token, dht::token, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > const&) at /usr/src/debug/scylla-3.0.3/sstables/leveled_manifest.hh:395 (discriminator 2)
std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > leveled_manifest::overlapping<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > >(schema const&, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > const&, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > const&) at /usr/src/debug/scylla-3.0.3/sstables/leveled_manifest.hh:382
 (inlined by) sstables::get_fully_expired_sstables(table&, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > const&, std::chrono::time_point<gc_clock, std::chrono::duration<int, std::ratio<1l, 1l> > >) at /usr/src/debug/scylla-3.0.3/sstables/compaction.cc:809
sstables::compaction::setup() at /usr/src/debug/scylla-3.0.3/sstables/compaction.cc:367
operator() at /usr/src/debug/scylla-3.0.3/sstables/compaction.cc:745
 (inlined by) apply at /usr/src/debug/scylla-3.0.3/seastar/core/apply.hh:35
 (inlined by) apply<sstables::compaction::run(std::unique_ptr<sstables::compaction>)::<lambda()> > at /usr/src/debug/scylla-3.0.3/seastar/core/apply.hh:43
 (inlined by) apply<sstables::compaction::run(std::unique_ptr<sstables::compaction>)::<lambda()> > at /usr/src/debug/scylla-3.0.3/seastar/core/future.hh:1309
 (inlined by) operator() at /usr/src/debug/scylla-3.0.3/seastar/core/thread.hh:315
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:316
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::thread_context::main() at /usr/src/debug/scylla-3.0.3/seastar/core/thread.cc:313
```

Which is weird since the schema does not use LCS.

```
grep compaction schema.cql 
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compaction = {'class': 'SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}```
