### ISSUE TITLE
Scylla-Setup command options

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla#4390]
sudo scylla_setup --setup-nic-and-disks --nic eth1 --no-raid-setup
is generating a scylla-server file with eth0

*Installation details* 
Scylla version (or git commit hash): 3.0.4
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CENTOS7.5

*Hardware details (for performance issues)*          I3.8xl
Platform (physical/VM/cloud instance type/docker): AWS
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count) 2

**Comment by mailmahee** [comment]
CC @glommer

**Comment by mailmahee** [comment]
[root@ip-10-148-44-228 sysconfig]# cat scylla-server 
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME="eth0"

# setup NIC's and disks' interrupts, RPS, XPS, nomerges and I/O scheduler (posix)
SET_NIC_AND_DISKS="yes"

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no

**Comment by mailmahee** [comment]
[root@ip-10-148-44-228 scylla.d]# cat cpuset.conf
# DO NO EDIT
# This file should be automatically configure by scylla_cpuset_setup
#
# CPUSET="--cpuset 0 --smp 1"
CPUSET="--cpuset 0-7 "
[root@ip-10-148-44-228 scylla.d]#
sudo scylla_setup --setup-nic-and-disks --nic eth1 --no-raid-setup
[root@ip-10-148-44-228 scylla.d]# cat perftune.yaml
cpu_mask: '0x000000ff'
mode: mq
nic: eth0
tune:

**Comment by mailmahee** [comment]
[root@ip-10-148-44-228 scylla]# grep -v "^$" /etc/scylla/scylla.yaml | grep -v "^#"
```
cluster_name: 'Test Cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    # Addresses of hosts that are deemed contact points. 
    # Scylla nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds: "10.148.45.86"
listen_address: 10.148.45.86
native_transport_port: 9042
server_encryption_options:
    internode_encryption: all
    certificate: /etc/scylla/tls/db.crt
    keyfile: /etc/scylla/tls/db.key
    truststore: /etc/scylla/tls/cadb.pem 
client_encryption_options:
    enabled: true
    certificate: /etc/scylla/tls/scylladb.crt
    keyfile: /etc/scylla/tls/scylladb.key
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 10.148.45.86
rpc_port: 9160
api_port: 10000
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
hints_directory: /var/lib/scylla/hints
 
hinted_handoff_enabled: false
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
listen_interface: eth1
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/
```
