### ISSUE TITLE
GossipingPropertyFileSnitch - unable to parse file cassandra-rackdc.properties 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#459]
```
ERROR [shard 0] snitch_logger - Failed to parse a properties file (cassandra-rackdc.properties). Halting...
Exiting on unhandled exception of type 'std::system_error': Error system:2 (No such file or directory)
```

configuration file
```
shlomi@localhost~/.ccm/urchin/node1$ cat ~/.ccm/urchin/node1/conf/cassandra-rackdc.properties 
dc=dc1
rack=RAC1
```

scylla.yaml

```
shlomi@localhost~/.ccm/urchin/node1$ cat ~/.ccm/urchin/node1/conf/scylla.yaml 
api_address: 127.0.0.1
auto_bootstrap: false
cluster_name: urchin
commitlog_directory: /home/shlomi/.ccm/urchin/node1/commitlogs
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: 8192
data_file_directories:
- /home/shlomi/.ccm/urchin/node1/data
endpoint_snitch: org.apache.cassandra.locator.GossipingPropertyFileSnitch
initial_token: null
listen_address: 127.0.0.1
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 127.0.0.1
rpc_port: 9160
saved_caches_directory: /home/shlomi/.ccm/urchin/node1/saved_caches
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 127.0.0.1
start_native_transport: true
storage_port: 7000
write_request_timeout_in_ms: 2000
```

aligned with 
http://docs.datastax.com/en/cassandra/2.1/cassandra/architecture/architectureSnitchGossipPF_c.html
