### ISSUE TITLE
web port 10000 is not exposed to other containers

### ISSUE THREAD

**Issue by itayB** [scylladb/scylla#4890]
*Installation details*
Scylla version (or git commit hash):
docker version 3.0.3

Here is my `docker-compose.yml` file:
```
version: '3'
services:
  db:
    image: scylladb/scylla:3.0.3
  test:
    image: python:3.7.3
    command: "bash -c \"until $$(curl --silent --head --fail http://db:10000/api-doc); do echo \"N/A\"; sleep 2; done\""

```

Running this compose file will end up with infinity "N/A" prints because Scylla web server is not available outside the `db` container.
On other hand if you running `curl` within `db` container, web-server IS available:
```
~ $ docker exec -it default_db_1 bash                                                                                                                                                                                                                                07:55:48

   _____            _ _       _____  ____
  / ____|          | | |     |  __ \|  _ \
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ <
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/
               __/ |
              |___/


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at:
	http://www.scylladb.com/doc/

[root@0fd8e27cac42 /]# curl --silent --head --fail http://localhost:10000/api-doc
HTTP/1.1 200 OK
Content-Length: 1074
Content-Type: application/json
Server: Seastar httpd
Date: 25 Aug 2019 04:56:38 GMT

```

I think that the reason is that the web-server is running with `127.0.0.1:10000` rather than `0.0.0.0:10000` by default. make sense?

**Comment by tzach** [comment]
@itayB you can use  `--api-address 0.0.0.0`
For example
```
docker run --name some-scylla -d scylladb/scylla --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
```

**Comment by itayB** [comment]
adding `--api-address 0.0.0.0` did the trick:

```
version: '3'
services:
  db:
    image: scylladb/scylla:3.0.3
    command: "--api-address 0.0.0.0"
  test:
    image: python:3.7.3
    command: "bash -c \"until $$(curl --output /dev/null --silent --head --fail http://db:10000/api-doc); do echo \"N/A\"; sleep 2; done\""
```

BTW, I want to use it as an indication that Scylla is up & healthy for my integration tests.
Can I assume that if I get 200 everything is ok? any better endpoint?
