### ISSUE TITLE
An ambiguous error resulted by a missing white space in YAML

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5091]
*Installation details*
Scylla version: 60656d1959f0caa4d313f12cc9d4c8d80ab28618

*Description*
A missing whitespace between `:` and the following value makes the YAML parser "join" the key, `:` and the value an interpret this combo as a single string.

As a result if a poor user forgets to put a whitespace in seeders list:
```
seed_provider:
    # Addresses of hosts that are deemed contact points. 
    # Scylla nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds:"17.1.2.3"    <--- this will be parsed as 'seeds:"17.1.2.3"'
```

So, instead of indicating this in some human readable way `scylla` will simply assume that `seeds` are not set at all and use a default `127.0.0.1` value resulting (at best) in the ambiguous 

```
rpc - client 127.0.0.1: fail to connect
```

**Comment by vladzcloudius** [comment]
It turns out that YAML errors are simply ignored by `scylla` code.

**Comment by vladzcloudius** [comment]
Apparently it's due to some weird backward compatibility (according to the commit message f1dd698600e1528123194ce7fb4ab4566552cc63).

@slivne @avikivity @glommer @tzach Current behaviour is quite confusing. To sum up issues at hands:
1) Even if we detect errors in scylla.yaml we would only log an ERROR and continue booting using the configuration from the file we know is ill-formed.
2) `seed_provider` parsing is particularly broken (as also described in the opening message): it would simply not detect that internal values are ill-formed. An example in the opening message is only one of ways internal values may be broken and we would not detect this.

## Proposal for a fix
1) If we detect that `scylla.yaml` is ill-formed at *ANY field* - log and exit.
2) Fix the `seed_provider` parsing enforcing the following syntax:
   - Only a single `seed_provider` is allowed.
   - No other keys except for `class_name` and `parameters` are allowed.
   - Only a single `- seeds: ...` entry is allowed.

For instance the following will be considered ill-formed:

```
seed_provider:
    # Addresses of hosts that are deemed contact points. 
    # Scylla nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds:"17.1.2.3" 
          - seeds:"17.1.2.4" 
```
