### ISSUE TITLE
Repair failed: rpc stream not found

### ISSUE THREAD

**Issue by mrdun** [scylladb/scylla#5201]
*Installation details*
Scylla version (or git commit hash): 3.0.10-0.20190815.b3bfd8c08
Cluster size: 6 nodes, Multi-DC
OS (RHEL/Oracle Linux 7.7):
Platform (DigitalOcean droplets):

We're getting such errors during repair for tables in keyspace on any node in cluster:
```
[shard 3] repair - Repair 1516 out of 1537 ranges, id=1, shard=3, keyspace=statistic, table={video_cumulative_rate}, range=(9032523639372596484, 9033438712938175185]
[shard 1] repair - Repair 1480 out of 1537 ranges, id=1, shard=1, keyspace=statistic, table={video_cumulative_rate}, range=(8667609191079127998, 8684370911008419183]
[shard 2] repair - Repair 1472 out of 1537 ranges, id=1, shard=2, keyspace=statistic, table={video_cumulative_rate}, range=(8523812571474943919, 8538254892129839818]
[shard 3] repair - Repair 1517 out of 1537 ranges, id=1, shard=3, keyspace=statistic, table={video_cumulative_rate}, range=(9033438712938175185, 9037745875139509420]
[shard 0] repair - Repair 1537 out of 1537 ranges, id=1, shard=0, keyspace=statistic, table={video_cumulative_rate}, range=(9215281419092747601, +inf)
[shard 3] repair - Repair 1518 out of 1537 ranges, id=1, shard=3, keyspace=statistic, table={video_cumulative_rate}, range=(9037745875139509420, 9051741468455137741]
[shard 0] repair - Start streaming for repair id=1, shard=0, index=0, ranges_in=115, ranges_out=575
[shard 0] stream_session - [Stream #37d29900-f3f0-11e9-8bce-000000000003] Executing streaming plan for repair-in-id-1-shard-0-index-0 with peers={134.209.168.22, 142.93.232.152, 159.8
9.39.8, 159.89.39.109, 188.166.84.20}, master
[shard 3] seastar - Exceptional future ignored: std::logic_error (rpc stream id 40004 not found), backtrace:   0x7d0358
                                                        0x5a5744
                                                        0x33b3d13
                                                        0x5a403e
                                                        0x5a4201
                                                        0x6728a7
                                                        0x67705a
                                                        0x75a0bd
                                                        /lib64/libpthread.so.0+0x7ea4
                                                        /lib64/libc.so.6+0xfe8cc
[shard 5] seastar - Exceptional future ignored: std::logic_error (rpc stream id 60000 not found), backtrace:   0x7d0358
                                                        0x5a5744
                                                        0x33af883
                                                        0x33b1028
                                                        0x33b3256
                                                        0x899e52
                                                        0x5a403e
                                                        0x5a4201
                                                        0x6728a7
                                                        0x67705a
                                                        0x75a0bd
                                                        /lib64/libpthread.so.0+0x7ea4
                                                        /lib64/libc.so.6+0xfe8cc
```
After error repair process freezes and never complete.

Something similar was in [#4953](https://github.com/scylladb/scylla/issues/4953), but our cluster didn't configured to use encrypted connections between DC.

Our cluster configuration:
```
cluster_name: 'cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 64
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "11.11.11.11,22.22.22.22,33.33.33.33,44.44.44.44"
listen_address: 10.10.10.2
broadcast_address: 22.22.22.22
listen_on_broadcast_address: True
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
authenticator: PasswordAuthenticator
broadcast_rpc_address: 22.22.22.22
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
concurrent_compactors: 6
internode_compression: dc
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/
enable_sstables_mc_format: true
```
