### ISSUE TITLE
cache is being populated in the write-only test

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5257]
*Installation details*
Scylla version: e621db591e41b9767468cb196ac4fc3ecbd4220c
Cluster size: 1
Shards count: 16
RAM: 4GB/shard
OS: Ubuntu 19.04

*Hardware details (for performance issues)*
Platform: AWS m5d.metal

*Description*
Scylla command: 
```
scylla --options-file /home/ubuntu/.ccm/scylla-1/node1/conf/scylla.yaml --log-to-stdout 1 --memory 64G --default-log-level info --cpuset 1-16 --smp 16 --developer-mode false --io-properties-file /home/ubuntu/.ccm/scylla-1/node1/conf/io_properties.yml --prometheus-address 10.0.0.14 --api-address 10.0.0.14 --collectd-hostname ip-10-0-0-14.node1 --collectd 0
```

scylla.yaml:
```
api_address: 10.0.0.14
api_port: 10000
auto_bootstrap: false
batch_size_fail_threshold_in_kb: 50
batch_size_warn_threshold_in_kb: 5
cas_contention_timeout_in_ms: 1000
cluster_name: scylla-1
commitlog_directory: /var/lib/scylla/commitlogs
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
data_file_directories:
- /var/lib/scylla/data
endpoint_snitch: SimpleSnitch
hints_directory: /var/lib/scylla/hints
initial_token: null
listen_address: 10.0.0.14
murmur3_partitioner_ignore_msb_bits: 12
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 10.0.0.14
rpc_port: 9160
saved_caches_directory: /var/lib/scylla/saved_caches
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 10.0.0.14
start_native_transport: true
storage_port: 7000
view_hints_directory: /var/lib/scylla/view_hints
write_request_timeout_in_ms: 2000
```

io_properties.yml:
```
disks:
- mountpoint: '/var/lib/scylla'
  read_iops: 765004
  read_bandwidth: 3525000000
  write_iops: 381329
  write_bandwidth: 1517000000
```

![image](https://user-images.githubusercontent.com/6103981/67984464-26eee980-fbfd-11e9-8cd4-de8243be46cf.png)

![image](https://user-images.githubusercontent.com/6103981/67984513-484fd580-fbfd-11e9-8d93-1327e5a67e76.png)
