### ISSUE TITLE
Upgrading Scylla from 3.0 to 3.1 while having `internode_compression: all` prevents node from joining cluster

### ISSUE THREAD

**Issue by jtnagashima** [scylladb/scylla#6205]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
Scylla version (or git commit hash): `scylla-server-3.0.11-0.20191126.3c91bad0d.el7.x86_64`
Cluster size: `5`
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ScyllaDB 2.3.1 (ami-0402378ae7131b7a0)`

**Issue**
While attempting to upgrade a cluster from Scylla 3.0 to 3.1, the first node would not join the cluster after installing Scylla 3.1. The logs would show: `scylla[18637]:  [shard 0] gossip - Connect seeds again ... (xxx seconds passed)` for as long as the value used in `shadow_round_ms` or 300 seconds default. Afterwards, the  scylla-server would shutdown:
```
[shard 0] gossip - Connect seeds again ... (299 seconds passed)
[shard 0] init - Shutdown database started
[shard 0]  scylla[31081]:  [shard 0] compaction_manager - Stopped
```

**The "Fix":**
Disabling the configuration option `internode_compression: all` from scylla.yaml allowed the node to successfully join the cluster.

**Comment by tomer-sandler** [comment]
Not sure if related but see this ticket as well: https://github.com/scylladb/scylla/issues/5963

**Comment by tomer-sandler** [comment]
More info from Slack:
```
Cluster was running with Scylla OSS 2.3 was upgraded to 3.0.11 with no problems with `internode_compression: all`
Single DC.
```

**Comment by tomer-sandler** [comment]
@jtnagashima if you can share the scylla logs and `scylla.yaml` files from all nodes that will help.
https://docs.scylladb.com/getting-started/logging/

**Comment by jtnagashima** [comment]
scylla.yaml
```
cluster_name: dev
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "x.x.x.1"
listen_address: x.x.x.4
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: x.x.x.4
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
internode_compression: all 
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_keyspace_column_family_metrics: true
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/
enable_sstables_mc_format: true
replace_address_first_boot: x.x.x.4 
```
