### ISSUE TITLE
Nodetool Repair failing on keyspace with std::runtime_error (row_diff.size() != set_diff.size())

### ISSUE THREAD

**Issue by jtnagashima** [scylladb/scylla#6252]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
Scylla version (or git commit hash): `scylla-3.3.0-0.20200319.7ae2cdf46c7.x86_64`
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ScyllaDB 2.3.1 (ami-0402378ae7131b7a0)
Single Datacenter 

**Issue**
We recently ran through an exercise of upgrading a 5 node cluster from Scylla 2.3.6 to 3.3.0. During the upgrade process, we encountered one other issue https://github.com/scylladb/scylla/issues/6205, but it was an otherwise seamless upgrade process.  Disclaimer: during the debug process for the issue, we did end up dropping a node - node 4, and re-adding it to the cluster as a fresh node as a replacement for itself using the `replace_address_first_boot` parameter.

After the nodes were upgraded, we ran `nodetool repair` on the nodes, beginning with node-4 and ran into the following error:
`[shard 1] repair - Got error in row level repair: std::runtime_error (row_diff.size() != set_diff.size())`

**Scylla.yaml**
```
cluster_name: dev
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "x.x.x.1"
listen_address: x.x.x.4
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: x.x.x.4
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_sstables_mc_format: true
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```
**Logs**
```
[shard 0] repair - repair id 2 failed: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-5370793244696977581, -5328668260210922544]), shard 1: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-932048315410807253, -858081057500917632]), shard 2: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-8207641162893696763, -8167358952841479574]), shard 3: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-4216530378557687254, -4193096228690490921])})
```
With trace level logging:
```
[shard 1] repair - Got error in row level repair: std::runtime_error (row_diff.size() != set_diff.size())
```
**Stacktrace**
```
java.lang.RuntimeException: Repair job has failed with the error message: [2020-04-20 16:03:52,966] Repair session 2 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```
