### ISSUE TITLE
Repair process hangs for 22 hours with no reason

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#6272]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200420.a4aa753f0f
Cluster size: 4 nodes (i3.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-03ce0a8634316edb0 (us-east-1)

Test: Longevity-lwt-basic-24h

Nemesis ```CorruptThenRepair``` was started at ```2020-04-21 17:13:17``` on the node 3:
```
< t:2020-04-21 17:13:17,194 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > 2020-04-21 17:13:17.182: (DisruptionEvent Severity.NORMAL): type=start name=CorruptThenRepair node=Node longevity-lwt-24h-repair-f-db-node-f9f57b49-3 [
54.165.67.21 | 172.30.0.112] (seed: False) duration=None
```

scylla-server was stopped and few data files were removed.

at ```t:2020-04-21 17:13:25,541``` scylla-server was started

Repair was started at ```2020-04-21 17:15:00``` (run ```nodetoll repair```):
```
< t:2020-04-21 17:15:00,562 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:14:49+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 0] repair - starting user-requested repair for keyspace cqlstress_lwt_example, repair id 1, options {{ trace -> false}, { incremental -> false}, { jobThreads -> 1}, { primaryRange -> false}, { parallelism -> parallel}}
```

Repair started:
```
< t:2020-04-21 17:15:00,562 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:14:49+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 0] repair - Repair 1 out of 770 ranges, id=1, shard=
0, keyspace=cqlstress_lwt_example, table={blogposts_update_two_columns_lwt_indicator_upd, blogposts_update_two_columns_lwt_indicator, blogposts_update_one_column_lwt_indicator_upd, blogposts_not_updated_lwt_indicator, blogposts_not_updat
ed_lwt_indicator_expect, blogposts_update_one_column_lwt_indicator, blogposts}, range=(-inf, -9199368603944808386]
< t:2020-04-21 17:15:00,563 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:14:49+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 0] repair - Repair 2 out of 770 ranges, id=1, shard=
0, keyspace=cqlstress_lwt_example, table={blogposts_update_two_columns_lwt_indicator_upd, blogposts_update_two_columns_lwt_indicator, blogposts_update_one_column_lwt_indicator_upd, blogposts_not_updated_lwt_indicator, blogposts_not_updat
ed_lwt_indicator_expect, blogposts_update_one_column_lwt_indicator, blogposts}, range=(-9181282243458509634, -9171169968769775138]

```

Last repair message received at ```2020-04-21 17:21:27```:
```
< t:2020-04-21 17:20:26,566 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:20:13+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 7] repair - repair id 1 on shard 7 completed successfully
< t:2020-04-21 17:20:26,660 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:20:15+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 2] repair - repair id 1 on shard 2 completed successfully
< t:2020-04-21 17:20:26,682 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:20:17+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 3] repair - repair id 1 on shard 3 completed successfully
< t:2020-04-21 17:20:26,757 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:20:18+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 5] repair - repair id 1 on shard 5 completed successfully
< t:2020-04-21 17:20:57,427 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:20:54+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 6] repair - repair id 1 on shard 6 completed successfully
< t:2020-04-21 17:21:27,578 f:cluster.py      l:1394 c:sdcm.cluster         p:DEBUG > 2020-04-21T17:21:21+00:00  longevity-lwt-24h-repair-f-db-node-f9f57b49-3 !INFO    | scylla: [shard 4] repair - repair id 1 on shard 4 completed successfully
```

There is no repair id 1 on shards _0_ and _1_

Now , at ```Apr 22 15:43:32 ``` the repair process is still alive:
```
[centos@longevity-lwt-24h-repair-f-db-node-f9f57b49-3 ~]$ ps -fe | grep 24324
centos   24324  3639  0 Apr21 ?        00:00:00 /bin/sh /opt/scylladb/share/cassandra/bin/nodetool repair
centos   24416 24324  0 Apr21 ?        00:01:02 java -javaagent:/opt/scylladb/share/cassandra/lib/jamm-0.3.2.jar -ea -cp /tmp/tmp.u0jnm83Mrk:/opt/scylladb/share/cassandra/lib/airline-0.6.jar:/opt/scylladb/share/cassandra/lib/antlr-runtime-3.5.2.jar:/opt/scylladb/share/cassandra/lib/apache-cassandra-666.development-20200420.2f73d3ae37.jar:/opt/scylladb/share/cassandra/lib/apache-cassandra.jar:/opt/scylladb/share/cassandra/lib/apache-cassandra-thrift-666.development-20200420.2f73d3ae37.jar:/opt/scylladb/share/cassandra/lib/asm-6.2.jar:/opt/scylladb/share/cassandra/lib/caffeine-2.2.6.jar:/opt/scylladb/share/cassandra/lib/chronicle-bytes-1.16.3.jar:/opt/scylladb/share/cassandra/lib/chronicle-core-1.16.3-SNAPSHOT.jar:/opt/scylladb/share/cassandra/lib/chronicle-queue-4.16.3.jar:/opt/scylladb/share/cassandra/lib/chronicle-threads-1.16.0.jar:/opt/scylladb/share/cassandra/lib/chronicle-wire-1.16.1.jar:/opt/scylladb/share/cassandra/lib/commons-cli-1.1.jar:/opt/scylladb/share/cassandra/lib/commons-codec-1.9.jar:/opt/scylladb/share/cassandra/lib/commons-lang3-3.1.jar:/opt/scylladb/share/cassandra/lib/commons-math3-3.2.jar:/opt/scylladb/share/cassandra/lib/compress-lzf-0.8.4.jar:/opt/scylladb/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/opt/scylladb/share/cassandra/lib/concurrent-trees-2.4.0.jar:/opt/scylladb/share/cassandra/lib/disruptor-3.0.1.jar:/opt/scylladb/share/cassandra/lib/ecj-4.6.1.jar:/opt/scylladb/share/cassandra/lib/guava-18.0.jar:/opt/scylladb/share/cassandra/lib/HdrHistogram-2.1.9.jar:/opt/scylladb/share/cassandra/lib/high-scale-lib-1.0.6.jar:/opt/scylladb/share/cassandra/lib/hppc-0.5.4.jar:/opt/scylladb/share/cassandra/lib/jackson-core-asl-1.9.13.jar:/opt/scylladb/share/cassandra/lib/jackson-mapper-asl-1.9.13.jar:/opt/scylladb/share/cassandra/lib/jamm-0.3.2.jar:/opt/scylladb/share/cassandra/lib/javax.inject.jar:/opt/scylladb/share/cassandra/lib/jbcrypt-0.3m.jar:/opt/scylladb/share/cassandra/lib/jcl-over-slf4j-1.7.7.jar:/opt/scylladb/share/cassandra/lib/jctools-core-1.2.1.jar:/opt/scylladb/share/cassandra/lib/jflex-1.6.0.jar:/opt/scylladb/share/cassandra/lib/jna-4.2.2.jar:/opt/scylladb/share/cassandra/lib/joda-time-2.4.jar:/opt/scylladb/share/cassandra/lib/json-simple-1.1.jar:/opt/scylladb/share/cassandra/lib/jstackjunit-0.0.1.jar:/opt/scylladb/share/cassandra/lib/libthrift-0.9.2.jar:/opt/scylladb/share/cassandra/lib/log4j-over-slf4j-1.7.7.jar:/opt/scylladb/share/cassandra/lib/logback-classic-1.1.3.jar:/opt/scylladb/share/cassandra/lib/logback-core-1.1.3.jar:/opt/scylladb/share/cassandra/lib/lz4-1.3.0.jar:/opt/scylladb/share/cassandra/lib/metrics-core-3.1.5.jar:/opt/scylladb/share/cassandra/lib/metrics-jvm-3.1.5.jar:/opt/scylladb/share/cassandra/lib/metrics-logback-3.1.5.jar:/opt/scylladb/share/cassandra/lib/netty-all-4.0.56.Final.jar:/opt/scylladb/share/cassandra/lib/ohc-core-0.5.1.jar:/opt/scylladb/share/cassandra/lib/ohc-core-j8-0.5.1.jar:/opt/scylladb/share/cassandra/lib/reporter-config3-3.0.3.jar:/opt/scylladb/share/cassandra/lib/reporter-config-base-3.0.3.jar:/opt/scylladb/share/cassandra/lib/scylla-driver-core-3.7.1-scylla-2-shaded.jar:/opt/scylladb/share/cassandra/lib/scylla-tools-666.development-20200420.2f73d3ae37.jar:/opt/scylladb/share/cassandra/lib/sigar-1.6.4.jar:/opt/scylladb/share/cassandra/lib/slf4j-api-1.7.7.jar:/opt/scylladb/share/cassandra/lib/snakeyaml-1.11.jar:/opt/scylladb/share/cassandra/lib/snappy-java-1.1.1.7.jar:/opt/scylladb/share/cassandra/lib/snowball-stemmer-1.3.0.581.1.jar:/opt/scylladb/share/cassandra/lib/ST4-4.0.8.jar:/opt/scylladb/share/cassandra/lib/stream-2.5.2.jar:/opt/scylladb/share/cassandra/lib/stress.jar:/opt/scylladb/share/cassandra/lib/thrift-server-0.3.7.jar:/opt/scylladb/share/cassandra/*.jar: -Xmx128m -XX:ParallelGCThreads=1 -Dcassandra.storagedir= -Dlogback.configurationFile=logback-tools.xml org.apache.cassandra.tools.NodeTool -p 7199 repair
```

The cluster is alive. Node IP (with stuck process): 54.165.67.21

node scylla.yaml:
```
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: false
batch_size_fail_threshold_in_kb: 50
batch_size_warn_threshold_in_kb: 5
broadcast_rpc_address: 172.30.0.112
cas_contention_timeout_in_ms: 1000
client_encryption_options:
  enabled: false
cluster_name: longevity-lwt-24h-repair-f-db-cluster-f9f57b49
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: org.apache.cassandra.locator.Ec2Snitch
experimental: true
listen_address: 172.30.0.112
murmur3_partitioner_ignore_msb_bits: 12
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 172.30.0.112
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 172.30.0.254
write_request_timeout_in_ms: 2000
```
