### ISSUE TITLE
docker image 3.3 does not create /var/lib/scylla/commitlog for some reason (change in behavior)

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla#6381]
## Problem
Apparently scylla 3.3 io_tune or some bootstrapping script is not creating the commitlog subdir. 
Not sure what the problem is but it is reproducible with docker-compose (see below)

Before running `docker-compose up -d`

Clean up the dirs on the host:
`for i in $(seq 1 4); do sudo rm -rf /mnt/$i/*; done`

### Error on 3.3

```
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/opt/scylladb/scripts/scylla_cpuset_setup', '--cpuset', '4'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
tuning /sys/devices/pci0000:00/0000:00:17.0/ata3/host3/target3:0:0/3:0:0:0/block/sdc/sdc1
tuning /sys/devices/pci0000:00/0000:00:17.0/ata3/host3/target3:0:0/3:0:0:0/block/sdc
tuning: /sys/devices/pci0000:00/0000:00:17.0/ata3/host3/target3:0:0/3:0:0:0/block/sdc/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:17.0/ata3/host3/target3:0:0/3:0:0:0/block/sdc/queue/nomerges to 2

ERROR:root:/var/lib/scylla/commitlog was not found. Please check the configuration and run scylla_io_setup again.

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 61, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 32, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
```

### docker-compose for 3.3 which does not work
```
version: '2'

services:
  scylladb-01:
    image: scylladb/scylla:3.3.1-202005050229
    networks:
      scylla_net:
        ipv4_address: 172.19.0.2
    container_name: scylladb-01
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc2.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/1:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 4 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    environment:
      - IP=172.19.0.2
    cap_add:
      - SYS_NICE

  scylladb-02:
    image: scylladb/scylla:3.3.1-202005050229
    networks:
      scylla_net:
        ipv4_address: 172.19.0.3
    container_name: scylladb-02
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc1.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/2:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 5 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-03:
    image: scylladb/scylla:3.3.1-202005050229
    networks:
      scylla_net:
        ipv4_address: 172.19.0.4
    container_name: scylladb-03
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc2.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/3:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 6 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-04:
    image: scylladb/scylla:3.3.1-202005050229
    networks:
      scylla_net:
        ipv4_address: 172.19.0.5
    container_name: scylladb-04
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc1.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/4:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 7 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

networks:
  scylla_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1
```

### Docker compose for scylla 2019.1 - it works
```
version: '2'

services:
  scylladb-01:
    image: scylladb/scylla-enterprise:2019.1.7
    networks:
      scylla_net:
        ipv4_address: 172.19.0.2
    container_name: scylladb-01
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc2.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/1:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 4 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    environment:
      - IP=172.19.0.2
    cap_add:
      - SYS_NICE

  scylladb-02:
    image: scylladb/scylla-enterprise:2019.1.7
    networks:
      scylla_net:
        ipv4_address: 172.19.0.3
    container_name: scylladb-02
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc1.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/2:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 5 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-03:
    image: scylladb/scylla-enterprise:2019.1.7
    networks:
      scylla_net:
        ipv4_address: 172.19.0.4
    container_name: scylladb-03
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc2.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/3:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 6 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-04:
    image: scylladb/scylla-enterprise:2019.1.7
    networks:
      scylla_net:
        ipv4_address: 172.19.0.5
    container_name: scylladb-04
    volumes:
      - ~/Bin/docker/scylla.yaml:/etc/scylla/scylla.yaml
      - ~/Bin/docker/cassandra-rackdc_dc1.properties:/etc/scylla/cassandra-rackdc.properties
      - /mnt/4:/var/lib/scylla
    command: "--seeds 172.19.0.2 --cpuset 7 --memory 2G --developer-mode 0 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

networks:
  scylla_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1
```

### cassandra-rackdc_dc1.properties
```
dc=DCA
rack=A1
prefer_local=true
```

### cassandra-rackdc_dc2.properties
```
dc=DCB
rack=B1
prefer_local=true
```

### scylla.yaml
```
# some_value: 'This Value' 
cluster_name: 'Docker Cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    # Addresses of hosts that are deemed contact points. 
    # Scylla nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds: "172.19.0.2,172.19.0.3"
listen_address: $(hostname -I)
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: $(hostname -I)
rpc_port: 9160
api_port: 10000
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
experimental: true
 
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/
```
