### ISSUE TITLE
scylla-housekeeping url encoding error

### ISSUE THREAD

**Issue by AnshumanTripathi** [scylladb/scylla#6690]
*Installation details*
Scylla version (or git commit hash): 4.0.2
Cluster size: 1
Platform (physical/VM/cloud instance type/docker): docker

I am creating the cluster using the following docker-compose
```
version: "3.8"
services:
  scylla-db-dev:
    image: scylladb/scylla:4.0.2
    restart: always
    container_name: scylla_dev
    networks:
      scylla-db:
    ports:
      - 9042:9042
    volumes:
      - /opt/scylla/dev:/var/lib/scylla
      - ./scylla.yaml:/etc/scylla/scylla.yaml
      - ./cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
networks:
  scylla-db:
    driver: bridge
```

I am seeing the following error when starting the cluster
```
...
JMX is enabled to receive remote connections on port: 7199
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 197, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 123, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 82, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 74, in get_json_from_url
    retval = result.get(timeout=5)
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fcc22421d90>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object")'
INFO  2020-06-22 02:40:50,027 [shard 0] init - loading non-system sstables
...
```
This error goes away when I remove the volume binding `/opt/scylla/dev:/var/lib/scylla`. I was seeing this with `scylladb/scylla:4.0.1` too. I don't think this is affecting any functionality in any way.

**Comment by slivne** [comment]
@amnonh can you please take a look

**Comment by amoskong** [comment]
I also see this error in a old scylla-nightly docker (666.development-0.20200310.d895f5e1311).
The first housekeeping call will be  executed at the beginning of node init, api server is ready. But if scylla-jmx isn't ready, the call might be failed.

We started scylla-housekeeping and scylla-jmx almost at same time. and scylla-housekeeping will sleep 5 seconds before calling the api.

And I didn't see this problem in latest scylla-nightly docker (666.development-0.20200521.c29ccdea7)

**Comment by amnonh** [comment]
@AnshumanTripathi I tried to reproduce it locally (I bind `/var/lib/scylla` to a local directory and I'm using version 3.7) without success.

The error you are seeing is from the housekeeping that tries to check for a newer version and faces some error (most likely a connectivity issue).
I'm not sure why it is related to the volume binding.
It does not affect any functionality

**Comment by amnonh** [comment]
@amoskong syclla housekeeping does not use the jmx, so I don't think it is related

**Comment by AnshumanTripathi** [comment]
@amnonh I could not find an image with tag 3.7, but I was able to reproduce it on version 3.3.4.

**Comment by fruch** [comment]
@amnonh I think it's relevant to the mount of older data dir, since scylla might take more time to finish booting, and some of the API call might be unresponsive at that time.

Anyhow it's just a but of us passing the exceptions between processes, we can just stop doing that, and just print it, since we should be retrying it anyhow.

@AnshumanTripathi I think @amnonh meant python3.7, not scylla 3.7

**Comment by AnshumanTripathi** [comment]
Aah didn't realize that. I have python 3.7.7 on my machine.

**Comment by amnonh** [comment]
With `version` I was referring to the docker file, because I suspect this is network reachability issue (housekeeping inside the container is unable to find what the latest version is) then the same problem will consist.

**Comment by AnshumanTripathi** [comment]
Actually running docker-compose with version "3.3", does not bubble up this error.

**Comment by AnshumanTripathi** [comment]
Just noticed this error is still popping up but at a different point even with docker-compose version 3.3

**Comment by slivne** [comment]
@AnshumanTripathi
- does this reproduce for you non locally on a cloud server GCE or AWS
- can you share your docker compose file so we can try and reproduce ...


@amnonh ping

**Comment by AnshumanTripathi** [comment]
@slivne I'm seeing this on local. I have not reproduced this on GCE or AWS. 
This is my docker-compose
```
version: "3.3"
services:
  scylla-db-dev:
    image: scylladb/scylla:4.0.3
    restart: always
    container_name: scylla_dev
    networks:
      scylla-db:
    ports:
      - 9042:9042
    volumes:
      - /opt/scylla/dev:/var/lib/scylla    # Error goes away when this volume binding is removed
      - ./scylla.yaml:/etc/scylla/scylla.yaml
      - ./cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties

networks:
  scylla-db:
    driver: bridge
```
Please note that this error goes away when I remove the `/opt/scylla/dev:/var/lib/scylla` volume binding.
