### ISSUE TITLE
Reads require +1 response more than writes at same consistency level (QUORUM)

### ISSUE THREAD

**Issue by kharmabum** [scylladb/scylla#6884]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
Scylla version (or git commit hash): `3.3.0-0.20200319.7ae2cdf46c7` 
Cluster size: `5`
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ScyllaDB 2.3.1 (ami-0402378ae7131b7a0)`

**Issue**
We’re using the datastax driver in a Kotlin web application with consistency level set to QUORUM. We’re running a 5 node cluster with RF set to 3. We’ve noticed that our reads and write require different response levels (e.g. 3 for reads and 2 for writes). We obviously expect both reads and write to require 2 responses each. See error messages below for read vs write:

**Read Timeout Exception**
```
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)
```

**Write Timeout Exception**
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

**scylla.yaml**
```
cluster_name: dev
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "x.x.x.1"
listen_address: x.x.x.4
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: x.x.x.4
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_sstables_mc_format: true
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```
