### ISSUE TITLE
Update hinted handoff configuration format to the newest Cassandra format

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#7048]
Our implementation of hinted handoff supports the old format for specifying towards which DCs hints are enabled. There is a single option 'hinted_handoff_enabled' that controls it. Examples:

```yaml
# Hint writing and sending is allowed towards all DCs
hinted_handoff_enabled: true

# Hint writing and sending is completely forbidden
hinted_handoff_enabled: false

# Hint writing and sending is allowed only towards nodes from datacenters "DC1" and "DC2"
hinted_handoff_enabled: DC1,DC2
```

In version 3.0, Cassandra switched to a new format which separates global on/off switch from a list of DCs. An example taken from [cassandra.yaml](https://github.com/apache/cassandra/blob/139ad44e8b53ed194ba4b47fbfae3484015034f9/conf/cassandra.yaml#L48-L55):

```yaml
# May either be "true" or "false" to enable globally
hinted_handoff_enabled: true

# When hinted_handoff_enabled is true, a black list of data centers that will not
# perform hinted handoff
# hinted_handoff_disabled_datacenters:
#    - DC1
#    - DC2
```

We should switch to the new format. It uses YAML types better, and it is compatible with current configuration format of Cassandra.

Although Cassandra switched to the new format in a backwards-incompatible way, we should consider introducing a transition period. We could deprecate the old format, support both old and new for some time, and remove the old one at some point.

Important note: the old format specified a list of DCs towards which hints were __enabled__. The new format specifies a list of DCs towards which hints are __disabled__.

Relevant Cassandra issues:
- [CASSANDRA-6157](https://issues.apache.org/jira/browse/CASSANDRA-6157) (implementation of the old format)
- [CASSANDRA-9035](https://issues.apache.org/jira/browse/CASSANDRA-9035) (implementation of the new format)
