### ISSUE TITLE
Replacement node not joining without clear reason

### ISSUE THREAD

**Issue by powellchristoph** [scylladb/scylla#7171]
- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.3.4-0.20200616.ec12331f116-1
Cluster size: 12 nodes, 6 in two regions
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 1604

I upgraded from `3.0.11` to `3.3.4` without issue. Shortly after the upgrade, I had a node failure and am attempting to replace it with the `replace_address_first_boot` as specified in the documentation. The replacement node starts, joins and appears to bootstrap. And then it just suddenly stops without reason. I see nothing logged or a generated coredump.

dead node - `18.237.149.244/10.3.124.208`
replacement node - `34.220.118.91/10.3.113.169`

Existing cluster showing the `DN` node.
```
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  3.86.149.198    2.31 TB    256          ?       f79c96d1-97dd-4944-a391-18d0e4e32794  1d
UN  3.92.20.61      2.27 TB    256          ?       03dffcce-c142-4df8-88c1-9eaf4c901817  1a
UN  54.158.135.122  2.46 TB    256          ?       bcf68340-d728-4466-8f99-c0630cea2587  1b
UN  3.93.24.71      2.32 TB    256          ?       af9e6fae-17d7-4257-a6ca-a77138ae3b38  1d
UN  3.90.184.37     2.38 TB    256          ?       194bdc3b-c67c-4da8-b49a-2c76953e1a2a  1a
UN  34.230.69.121   2.22 TB    256          ?       fff68fed-4847-4c72-a9c4-44c2effce13a  1b
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  54.245.47.68    2.43 TB    256          ?       dafc728a-175c-4e7b-b260-4eb6e8998088  2a
UN  54.187.215.45   1.35 TB    256          ?       b3e5635b-82c3-4e15-8198-4f5af7693310  2b
UN  34.211.221.36   2.2 TB     256          ?       a85a9f60-6cd0-4759-8b90-46c2d466f781  2a
UN  54.213.177.77   2.5 TB     256          ?       414bbcdd-bff9-458e-a01f-979f63f3c1fa  2b
DN  18.237.149.244  ?          256          ?       4e1e3c8f-2be7-49b3-b120-8ec42a28b115  2c
UN  34.216.49.195   2.27 TB    256          ?       1ad891e5-52ab-4fde-85c3-1844b7855e76  2b
```

Replacement node config with `replace_address_first_boot` set.
```
---
auto_bootstrap: true
cluster_name: analytics
num_tokens: 256
data_file_directories:
- "/var/lib/scylla/data"
commitlog_directory: "/var/lib/scylla/commitlog"
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
listen_address: 10.3.113.169
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2MultiRegionSnitch
rpc_address: 10.3.113.169
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: 30719
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: "/usr/lib/scylla/swagger-ui/dist/"
api_doc_dir: "/usr/lib/scylla/api/api-doc/"
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 3.90.184.37,54.158.135.122,3.93.24.71,34.211.221.36,34.216.49.195,54.187.215.45
broadcast_address: 34.220.118.91
broadcast_rpc_address: 10.3.113.169
server_encryption_options:
  internode_encryption: all
  certificate: "/etc/scylla/scylla.crt"
  keyfile: "/etc/scylla/scylla.key"
  truststore: "/etc/scylla/truststore.pem"
replace_address_first_boot: 18.237.149.244
```

Replacement node log file with the compaction messages grep'd out.
https://gist.github.com/powellchristoph/a9afd24d0c85579af40808ed39b143cb

Logged from other nodes in the cluster
```

Sep 04 18:32:50 scylla-scorecard-n01 scylla[12692]:  [shard 0] gossip - InetAddress 34.220.118.91 is now UP, status = hibernate
Sep 04 18:34:07 scylla-scorecard-n01 scylla[12692]:  [shard 0] rpc - client 10.3.113.169:7001: fail to connect: Connection refused
Sep 04 18:34:12 scylla-scorecard-n01 scylla[12692]:  [shard 0] rpc - client 10.3.124.208:7001: fail to connect: Connection timed out
Sep 04 18:34:27 scylla-scorecard-n01 scylla[12692]:  [shard 0] gossip - InetAddress 34.220.118.91 is now DOWN, status = hibernate
Sep 04 18:34:28 scylla-scorecard-n01 scylla[12692]:  [shard 0] rpc - client 10.3.113.169:7001: fail to connect: Connection refused
Sep 04 18:34:32 scylla-scorecard-n01 scylla[12692]:  [shard 0] gossip - FatClient 34.220.118.91 has been silent for 30000ms, removing from gossip
```
