### ISSUE TITLE
Alternator: server certificate configuration is not being used

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla#7204]
*Installation details*
Scylla version (or git commit hash): 4.1.0-0.20200618.b443b2574a8

scylla.yaml:
```
alternator_https_port: 8000
client_encryption_options:
    enabled: true
    certificate: /etc/scylla/db.crt
    keyfile: /etc/scylla/db.key
```

Scylla is failing to boot up because it can't find (probably hardcoded) cert file different then configured one:
`ERROR 2020-09-09 10:25:50,368 [shard 0] init - Startup failed: std::_Nested_exception<std::runtime_error> (Could not read certificate file /etc/scylla/scylla.crt): std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/etc/scylla/scylla.crt])
`
