### ISSUE TITLE
GKE: scylla that is ran by scylla-operator has too many 7000 connections

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#7504]
By some reason scylla that is ran by scylla-operator on GKE spanning tons of 7000 connections up until limit is reached, it is not happening on minikube.

Scylla command line:

```
root          70  500 49.0 17180056456 15147404 ? Sl  07:25 696:13 /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --smp 6 --listen-address 10.142.0.106 --rpc-address 10.142.0.106 --seed-provider-parameters seeds=10.67.245.12,10.67.244.65 --broadcast-address 10.67.245.12 --broadcast-rpc-address 10.67.245.12 --blocked-reactor-notify-ms 999999999
```

scylla.yaml:

```
alternator_enforce_authorization: false
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: true
batch_size_fail_threshold_in_kb: 50
batch_size_warn_threshold_in_kb: 5
cas_contention_timeout_in_ms: 1000
client_encryption_options:
  enabled: false
cluster_name: sct-cluster
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: GossipingPropertyFileSnitch
experimental: true
listen_address: localhost
murmur3_partitioner_ignore_msb_bits: 12
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 0.0.0.0
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 127.0.0.1
write_request_timeout_in_ms: 2000
```

Number of 7000 connections:

```
lsof -nP | grep 7000 | grep ESTABLISHED -c
1200
```

[7000_connections.zip](https://github.com/scylladb/scylla/files/5457472/7000_connections.zip)

*Installation details*
Scylla version (or git commit hash): 4.1.7
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): kubernetes/docker
