### ISSUE TITLE
oversized request (length $A) submitted. dazed and confuzed, trimming its weight from $B down to $C

### ISSUE THREAD

**Issue by korjjj** [scylladb/scylla#8496]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 4.4
Cluster size: 32
OS:  CentOS

Platform VM
Disks: SSD, 1 disk

redirected from slack

After upgrading the first node in the cluster from 4.3 to 4.4 logs are spammed with:
```
[shard 0] io - (rate limiting dropped 217 similar messages) oversized request (length 32768) submitted. dazed and confuzed, trimming its weight from 8192 down to 4174
```
After (re)running 'scylla_setup' and 'perftune.py' number of reported 'dropped similar messages' went from 150-300 to 5-30:
```
[shard 0] io - (rate limiting dropped 12 similar messages) oversized request (length 98304) submitted. dazed and confuzed, trimming its weight from 25920 down to 25017
```

**Comment by xemul** [comment]
Can you attach your `io_properties.yaml` file, @korjjj

**Comment by korjjj** [comment]
```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 41921
    read_bandwidth: 264710528
    write_iops: 32166
    write_bandwidth: 257253568
```
