### ISSUE TITLE
support CRL with server/client encryption options

### ISSUE THREAD

**Issue by ajmaidak** [scylladb/scylla#9630]
Best I can tell scylla doesn't support a certificate revocation list for either server or client encryption options.  Thus if a TLS client private key is leaked you would need to remove the signing CA from the trust store to decline connections from clients using that certificate.  Ideally you would append the leaked clients certificate the CRL instead.

It would be a good enhancement to support providing a CRL file argument to the `client_encryption_options` and `server_encryption_options` configuration hashes, like:

```
client_encryption_options:
    enabled: True
    certificate: conf/scylla.crt
    keyfile: conf/scylla.key
    truststore: conf/truststore.pem
    certficate_revocation_list: conf/revoked-certs.crl
    require_client_auth: True
```
