### ISSUE TITLE
Node fails to start: Operation timed out for system_distributed_everywhere.cdc_generation_descriptions_v2

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#9653]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20211107.4950ce539 with build-id 8d7a7f85964575a8775f8358cef3ff74141e07fd
Cluster size: 9, split between 3 dc's: 4, 3 and 2 on eu-west-1, us-west-2, us-east-1 respectively.
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-059ce9f5311c1f755 ami-0515872fec42d763c ami-09170b5e7a8dbaea9 on eu-west-1, us-west-2, us-east-1 respectively.
Test case: https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-lwt-24h-multidc.yaml

The first node of the run (54.72.180.96 | 10.0.1.198) started with no issue. The second node (54.75.114.234 | 10.0.1.39), however, failed to start altogether, due to the following:
```
2021-11-15T12:05:55+00:00 lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-2 !ERR | scylla: [shard 0] init - Startup failed: exceptions::mutation_write_timeout_exception (Operation timed out for system_distributed_everywhere.cdc_generation_descriptions_v2 - received only 1 responses from 2 CL=ALL.)
```

The nodes were kept alive:
```
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-1 [54.72.180.96 | 10.0.1.198]
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-2 [54.75.114.234 | 10.0.1.39]
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-3 [34.241.165.213 | 10.0.2.233]
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-4 [3.250.167.195 | 10.0.2.188] 
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-5 [35.86.177.1 | 10.0.1.87] 
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-6 [52.33.121.139 | 10.0.1.93] 
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-7 [54.184.35.197 | 10.0.0.139] 
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-8 [3.239.70.88 | 10.0.3.146] 
lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-9 [3.239.222.71 | 10.0.1.171]
```

### Please let me know when I can terminate them

Logs:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                             Log links for testrun with test id d67a2920-93bc-4fd1-9c2d-3b9d60b54f98                                             |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                            |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| 20211115_130630 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/d67a2920-93bc-4fd1-9c2d-3b9d60b54f98/20211115_130630/db-cluster-d67a2920.tar.gz  |
| 20211115_130630 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/d67a2920-93bc-4fd1-9c2d-3b9d60b54f98/20211115_130630/loader-set-d67a2920.tar.gz  |
| 20211115_130630 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/d67a2920-93bc-4fd1-9c2d-3b9d60b54f98/20211115_130630/monitor-set-d67a2920.tar.gz |
| 20211115_130630 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/d67a2920-93bc-4fd1-9c2d-3b9d60b54f98/20211115_130630/sct-runner-d67a2920.tar.gz  |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment]
I started to debug 

the issue seems to be related to node encryption

```
scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-1:~$ cat /etc/scylla/scylla.yaml
alternator_enforce_authorization: false
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: true
batch_size_fail_threshold_in_kb: 1024
batch_size_warn_threshold_in_kb: 128
broadcast_address: 54.72.180.96
broadcast_rpc_address: 54.72.180.96
cas_contention_timeout_in_ms: 1000
client_encryption_options:
  certificate: /etc/scylla/ssl_conf/client/test.crt
  enabled: true
  keyfile: /etc/scylla/ssl_conf/client/test.key
  truststore: /etc/scylla/ssl_conf/client/catest.pem
cluster_name: lwt-longevity-multi-dc-24h-4-5-db-cluster-d67a2920
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: Ec2MultiRegionSnitch
experimental: true
listen_address: 10.0.1.198
murmur3_partitioner_ignore_msb_bits: 12
native_shard_aware_transport_port: 19042
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 10.0.1.198
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 54.72.180.96
server_encryption_options:
    certificate: /etc/scylla/ssl_conf/db.crt
    internode_encryption: dc
    keyfile: /etc/scylla/ssl_conf/db.key
    truststore: /etc/scylla/ssl_conf/cadb.pem
write_request_timeout_in_ms: 2000
```

If I comment out the server_encryption part - the node2 boots and its fine

If I change the scylla.yaml

```
alternator_enforce_authorization: false
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: true
batch_size_fail_threshold_in_kb: 1024
batch_size_warn_threshold_in_kb: 128
broadcast_address: 54.75.114.234
broadcast_rpc_address: 54.75.114.234
cas_contention_timeout_in_ms: 1000
client_encryption_options:
  certificate: /etc/scylla/ssl_conf/client/test.crt
  enabled: true
  keyfile: /etc/scylla/ssl_conf/client/test.key
  truststore: /etc/scylla/ssl_conf/client/catest.pem
cluster_name: lwt-longevity-multi-dc-24h-4-5-db-cluster-d67a2920
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: Ec2MultiRegionSnitch
experimental: true
listen_address: 10.0.1.39
murmur3_partitioner_ignore_msb_bits: 12
native_shard_aware_transport_port: 19042
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 10.0.1.39
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 54.72.180.96
server_encryption_options:
      certificate: /etc/scylla/ssl_conf/db.crt
      internode_encryption: all
      keyfile: /etc/scylla/ssl_conf/db.key
      truststore: /etc/scylla/ssl_conf/cadb.pem
write_request_timeout_in_ms: 2000
```

If update it to be with all it works fine node2 boots up as well.

The issue seems to be with the "dc" option for server-server encryption. 


```
scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-2:~$ nodetool status
Datacenter: eu-westscylla_node_west
===================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  54.75.114.234  527.93 KB  256          ?       95b68b7c-31bc-463f-a804-3becd4de0872  1a
UN  54.72.180.96   248.1 KB   256          ?       ef318005-a23f-4ebb-944d-53f9dfc133f6  1a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```


```
scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-1:~$ nodetool status
Datacenter: eu-westscylla_node_west
===================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  54.75.114.234  527.93 KB  256          ?       95b68b7c-31bc-463f-a804-3becd4de0872  1a
UN  54.72.180.96   248.1 KB   256          ?       ef318005-a23f-4ebb-944d-53f9dfc133f6  1a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```


both nodes are in the same rack - so they are supposed to use the non encrypted connection when its setup with "dc" 

![Screenshot from 2021-11-18 18-48-29](https://user-images.githubusercontent.com/3465480/142459544-28ffe8fc-367d-4e21-a04b-cf3880ca4b86.png)



but maybe its not working like that at boot time.

In any case this seems to be an issue with server-server encryption using "dc" option 

Please note that we are using Ec2MultiRegionSnitch and also have
```
scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-2:~$ cat /etc/scylla/cassandra-rackdc.properties 
#
# cassandra-rackdc.properties
#
# The lines may include white spaces at the beginning and the end.
# The rack and data center names may also include white spaces.
# All trailing and leading white spaces will be trimmed.
#  
# dc=my_data_center
# rack=my_rack
# prefer_local=<false | true>
# dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>
#


 

dc=eu-west-1
rack=RACK1
prefer_local=true
dc_suffix=scylla_node_west

scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-2:~$ 
```

```
scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-1:~$ cat /etc/scylla/cassandra-rackdc.properties 
#
# cassandra-rackdc.properties
#
# The lines may include white spaces at the beginning and the end.
# The rack and data center names may also include white spaces.
# All trailing and leading white spaces will be trimmed.
#  
# dc=my_data_center
# rack=my_rack
# prefer_local=<false | true>
# dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>
#


 

dc=eu-west-1
rack=RACK1
prefer_local=true
dc_suffix=scylla_node_west

scyllaadm@lwt-longevity-multi-dc-24h-4-5-db-node-d67a2920-1:~$ 

```

(seems to be the same for both nodes)
